# Generated by Django 4.1.5 on 2023-02-01 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0002_job_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="user",
            new_name="executor",
        ),
        migrations.AddField(
            model_name="job",
            name="completed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="owner",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="my_jobs_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="started_at",
            field=models.DateTimeField(null=True),
        ),
    ]
