# Generated by Django 4.1.5 on 2023-02-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_rename_title_jobcategory_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="counterpart_address",
            new_name="executor_address",
        ),
        migrations.AddField(
            model_name="job",
            name="status_id",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Open"), (2, "Waiting"), (3, "At work"), (4, "Completed")],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="amount",
            field=models.PositiveIntegerField(),
        ),
    ]
