# Generated by Django 4.1.5 on 2023-02-02 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0005_rename_counterpart_address_job_executor_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="executor_address",
            field=models.CharField(default="", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="status_id",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "open"),
                    (2, "waiting"),
                    (3, "at work"),
                    (4, "completed"),
                    (5, "canceled"),
                ],
                default=1,
            ),
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("address", models.CharField(default="", max_length=250, null=True)),
                (
                    "status_id",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "waiting"), (2, "accepted")], default=1
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "proposal",
                "verbose_name_plural": "proposals",
                "ordering": ["-id"],
            },
        ),
    ]
