# Generated by Django 4.1.5 on 2023-02-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_proposal_job_alter_proposal_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proposal",
            options={
                "ordering": ["id"],
                "verbose_name": "proposal",
                "verbose_name_plural": "proposals",
            },
        ),
        migrations.AddField(
            model_name="job",
            name="assigned_at",
            field=models.DateTimeField(null=True),
        ),
    ]
